version: '3.6'

services:
  song-database:
    container_name: song-database
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=songs
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '54322:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local