
services:
  song-service:
    url: http://song-service:8081
  resource-service:
    url: http://resource-service:8082

kafka:
  server:
    kafka:9092
  group:
    id: server.broadcast
  producer:
    name: resources

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.apache.kafka: INFO