spring:
  datasource:
    url: jdbc:postgresql://localhost:54321/resources
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: on
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

aws:
  url: http://localhost:4566
  access-key: test
  secret: test
  region: us-west-2

  s3:
    bucket-name: songs